#!/usr/bin/env python3
#####################################
# Installation module for Bloodhound
#####################################

# AUTHOR OF MODULE NAME
AUTHOR=""

# DESCRIPTION OF THE MODULE
DESCRIPTION=""

# INSTALL TYPE GIT, SVN, FILE DOWNLOAD
# OPTIONS = GIT, SVN, FILE
INSTALL_TYPE="FILE"

# LOCATION OF THE FILE OR GIT/SVN REPOSITORY
REPOSITORY_LOCATION="https://raw.githubusercontent.com/brightio/penelope/refs/heads/main/penelope.py"

# EXTENSION OF THE RELEASE FILE (WITHOUT ".")
RELEASE_EXTENSION=""

# FILTER TO GRAB THE CORRECT RELEASE FILE
RELEASE_FILTER=""

# WHERE DO YOU WANT TO INSTALL IT
INSTALL_LOCATION="penelope"

# DEPENDS FOR DEBIAN INSTALLS
DEBIAN=""

# DEPENDS FOR FEDORA INSTALLS
FEDORA=""

# COMMANDS TO RUN AFTER
AFTER_COMMANDS="cd {INSTALL_LOCATION},chmod +x penelope.py"

# THIS WILL CREATE AN AUTOMATIC LAUNCHER FOR THE TOOL
LAUNCHER="penelope"

# RUN AFTER_COMMAND AFTER UPDATING
BYPASS_UPDATE="YES"